name: Deploy to Firebase on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node.js環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Functionsの依存関係をインストール
      - name: Install Function Dependencies
        run: npm ci
        working-directory: ./functions

      # Google Cloudへの認証
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TYPING_GAME_A8239 }}

      # Firebaseにデプロイ
      - name: Deploy to Firebase
        uses: google-github-actions/deploy-firebase@v0
        with:
          project_id: typing-game-a8239
          args: deploy --only hosting,functions
